-- ***** RADIO **********************************************
local tradCOM1ACT   = Text.new("122.800",	TXT_18B_C, {"#00FF00"},              4, 830, 92, 18, tCONST)
local tradCOM1STB   = Text.new("122.800",	TXT_14B_C, {"#CCCCCC"},              4, 850, 92, 18, tCONST)
local tradCOM2ACT   = Text.new("122.800",	TXT_18B_C, {"#00FF00"},            575, 830, 92, 18, tCONST)
local tradCOM2STB   = Text.new("122.800",	TXT_14B_C, {"#CCCCCC"},            575, 850, 92, 18, tCONST)
local tradNAV1ACT   = Text.new("109.60",	TXT_18B_C, {"#00FF00"},             98, 830, 92, 18, tCONST)
local tradNAV1STB   = Text.new("109.60",	TXT_14B_C, {"#CCCCCC"},             98, 850, 92, 18, tCONST)
local tradNAV2ACT   = Text.new("109.60",	TXT_18B_C, {"#00FF00"},            475, 830, 92, 18, tCONST)
local tradNAV2STB   = Text.new("109.60",	TXT_14B_C, {"#CCCCCC"},            475, 850, 92, 18, tCONST)
local tradADF1ACT   = Text.new("1200.0",	TXT_18B_C, {"#00FF00"},            273, 830, 92, 18, tCONST)
local tradADF1STB   = Text.new("387.0",		TXT_14B_C, {"#CCCCCC"},            273, 850, 92, 18, tCONST)
local tradADF1mode  = Text.new("OFF",		TXT_14B_C, {"#00FFFF"},            273, 868, 92, 18, tCONST)
local tradADF2ACT   = Text.new("1200.0",	TXT_18B_C, {"#00FF00"},            373, 830, 92, 18, tCONST)
local tradADF2STB   = Text.new("387.0",		TXT_14B_C, {"#CCCCCC"},            373, 850, 92, 18, tCONST)
local tradADF2mode  = Text.new("OFF",		TXT_14B_C, {"#00FFFF"},            373, 868, 92, 18, tCONST)
local tradXPDRCODE  = Text.new("3000",		TXT_18B_C, {"#00FF00","#CCCCCC"},  182, 830, 92, 18, tCONST)
local tradXPDRMODE  = Text.new("OFF",		TXT_14B_C, {"#00FFFF"},            182, 850, 92, 18, tCONST)
local tradXPDRID    = Text.new("IDENT",		TXT_14B_C, {"#00FFFF"},            182, 868, 92, 18, tOPTIONAL)
local iradBOX       = Image.new("BOX_RADIO.png",                                13, 849, 76, 20, tOPTIONAL)


xpl_dataref_subscribe("sim/cockpit2/radios/actuators/com1_frequency_hz_833",         "INT", function(v) tradCOM1ACT:text(limit(v/1000,3)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/com1_standby_frequency_hz_833", "INT", function(v) tradCOM1STB:text(limit(v/1000,3)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/com2_frequency_hz_833",         "INT", function(v) tradCOM2ACT:text(limit(v/1000,3)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/com2_standby_frequency_hz_833", "INT", function(v) tradCOM2STB:text(limit(v/1000,3)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/nav1_frequency_hz",             "INT", function(v) tradNAV1ACT:text(limit(v/100,2)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/nav1_standby_frequency_hz",     "INT", function(v) tradNAV1STB:text(limit(v/100,2)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/nav2_frequency_hz",             "INT", function(v) tradNAV2ACT:text(limit(v/100,2)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/nav2_standby_frequency_hz",     "INT", function(v) tradNAV2STB:text(limit(v/100,2)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf1_frequency_hz",             "INT", function(v) tradADF1ACT:text(limit(v,1)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf1_standby_frequency_hz",     "INT", function(v) tradADF1STB:text(limit(v,1)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf1_power",                    "INT", function(v) tradADF1mode:text(v == 0 and "OFF" or (v < 3 and (v == 1 and "ANT" or "ON") or (v == 3 and "BFO" or "TEST"))) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf2_frequency_hz",             "INT", function(v) tradADF2ACT:text(limit(v,1)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf2_standby_frequency_hz",     "INT", function(v) tradADF2STB:text(limit(v,1)) end)
xpl_dataref_subscribe("sim/cockpit2/radios/actuators/adf2_power",                    "INT", function(v) tradADF2mode:text(v == 0 and "OFF" or (v < 3 and (v == 1 and "ANT" or "ON") or (v == 3 and "BFO" or "TEST"))) end)
xpl_dataref_subscribe("sim/cockpit/radios/transponder_code",     "INT", function(v) tradXPDRCODE:text(string.format("%04d", v)) end)
xpl_dataref_subscribe("sim/cockpit/radios/transponder_mode",     "INT", function(v) tradXPDRMODE:text(v == 0 and "OFF" or (v < 3 and (v == 1 and "STBY" or "ON") or (v == 3 and "TA" or "TA/RA"))) 
                                                                                    tradXPDRCODE:colorindex(v > 1 and 1 or 2) end)
xpl_dataref_subscribe("sim/cockpit/radios/transponder_id",       "INT", function(v) tradXPDRID:showElem(v > 0) end)
xpl_dataref_subscribe("cl300/mfd_sel_state", "INT", "cl300/mfd_sel_column", "INT", 
    function(s,c)
        if s > 0 then
            iradBOX:showElem(true)
            if c     == 0 then iradBOX:moveabs(13, 849)
            elseif c == 1 then iradBOX:moveabs(107, 849)
            elseif c == 2 then iradBOX:moveabs(191, 830)
            elseif c == 3 then iradBOX:moveabs(282, 849)
            elseif c == 4 then iradBOX:moveabs(382, 849)
            elseif c == 5 then iradBOX:moveabs(484, 849)
            elseif c == 6 then iradBOX:moveabs(584, 849)
            else               iradBOX:showElem(false) 
            end
        else
            iradBOX:showElem(false)
        end
    end)
